export const UPDATE_LABLIST = "UPDATE_LABLIST";
export const UPDATE_COULIST = "UPDATE_COULIST";
export const UPDATE_SELLECT = "UPDATE_SELLECT";
export const UPDATE_DIS = "UPDATE_DIS";
export const TRANSPLANT_COU = "TRANSPLANT_COU";
export const TRANSPLANT_LAB = "TRANSPLANT_LAB";
export const UPDATE_LABKEY = "UPDATE_LABKEY";
export const UPDATE_COUSKEY = "UPDATE_COUSKEY";
